### PR TITLE
Added modern macOS vibrance window style

### PR DESCRIPTION
**Pull request by polarlighthouse**
Added the parameters "vibrance" [none|light|dark], which changes the subview to NSVisualEffectView.
This should serve as a styling option to the deprecated "metal" window look.

Vibrancy will not work if transparency is below 1.0.

Also another paramter for setting the "titlebar" [true|false] is available.

*.vibrance = light
*.titlebar = 0
bildschirmfoto 2018-06-03 um 15 13 17

*.vibrance = dark
*.titlebar = 0
bildschirmfoto 2018-06-03 um 15 13 36

*.titlebar = 0
(no vibrance declared)
bildschirmfoto 2018-06-03 um 16 54 41

For more details:
[https://developer.apple.com/documentation/appkit/nsvisualeffectview](https://developer.apple.com/documentation/appkit/nsvisualeffectview)

### CODE REVIEW

**Comment by polarlighthouse** [comment]
I've edited the code for the pull request to match the existing format.

It's now possible to set the [light|dark|metal] appearance for the window. Vibrancy is called independently via *.vibrant = [0|1]. If vibrancy is set, an appearance variable is needed.

This gives the option to create non-vibrant dark UIs.

bildschirmfoto 2018-06-04 um 19 03 30

**Comment by BlueM** [comment]
Thanks for your PR (the 1st one ever for Pashua). I like re-using `appearance` for the vibrant theme, but I am not quite happy with the need to specify `appearance` when I activate vibrancy. As those settings are coupled anyway, what do you think about coupling them via the possible values for `appearance`? In other words, following that approach, the list of values would be:

* `light` (= default, if `appearance` is not specified)
* `light-vibrant`
* `dark`
* `dark-vibrant`
* `metal`

And another note: as you say that vibrancy and transparency are mutually exclusive, could you add a check which ensures that transparency XOR vibrancy is used, and just throw an exception (with a sensible message) to inform the user that the configuration doesn’t make sense? This should just be a matter of `[NSException raise:EXC_CONFIG format:your_new_localized_message];`

**Comment by polarlighthouse** [comment]
I agree, that way it's much cleaner and easier to define. 

I've adjusted the code, added the exception in PshWindow.m, Pashua_Prefix.pch and dict.strings.
The Exception gets raised when -vibrant and transparency is configured but it ignores the localized strings

Am I missing something?

bildschirmfoto 2018-06-10 um 13 17 50

Pashua_Prefix.pch
`#define PHR_CFGVIBRANTCONFL NSLocalizedStringFromTable(@"Cfg vibrant invalid", @"dict", @"Error msg: Appearance configuration is invalid")
`

dict.strings (German)
`/* Error msg: */
"Cfg vibrant invalid" = "Konfigurationsfehler: Die Vibrant-Darstellung kann nicht mit einer Transparenz definiert werden.";`

**Comment by BlueM** [comment]
Hard to say – it seems you haven’t committed and/or pushed the change involving the localization string. If you’ll do that, I can take a look.

**Comment by polarlighthouse** [comment]
Thanks for fixing it, Carsten. I'm looking forward to your solution - I didn't wanted to push unfinished/broken code into the repository

**Comment by BlueM** [comment]
The localization worked for me out of the box. (Note aside: If you take a look at https://github.com/BlueM/Pashua/pull/8/files#diff-5f5713184984421c21ed5f91e03ad480R50, you’ll see that there’s rubbish inserted – probably from the clipboard. I am on Xcode 9.2 and macOS 10.12 – maybe you’re on 9.3, and 9.3 doesn’t like this. But this is just a guess. However, the localization string declared in the line in question was not used anymore, anyway, so I just removed it.) I added a French translation for your configuration check, so the translations should be fine now.

Second: most of what you committed is supported only on 10.10+, so I put all of it in a check for OS X >= 10.10 and removed a bit of redundancy from the code.

Third: if you take a look at https://github.com/BlueM/Pashua/blob/polarlighthouse-Pashua-vibrance/PshWindow.m#L103 (now in a branch on the Pashua repository), shouldn’t that be `NSAppearanceNameAqua` instead of `NSAppearanceNameVibrantLight`? (Apart from the fact that the condition still has at least 1 redundancy and can be simplified.)

**Comment by polarlighthouse** [comment]
Thanks for pointing this out; I've fixed the issues. 

I wasn't aware of `NSAppearanceNameAqua` since it results in the same way as `NSAppearanceNameVibrantLight` does.
Hence, the "light" and "light-vibrance" conditions could be unified as vibrancy is defined after `// Vibrancy setup` – at least what I thought – which would result in a simple "== 'light' || "light-vibrant" condition.

However, from the docs the main difference is:
> Don't assign an NSAppearance object with this type directly to one of your views. Instead, assign a light appearance to your view, make sure its allowsVibrancy property is set to YES, and embed the view in a visual effect view. When you do, AppKit updates your view's appearance to this type.

I've got the same setup as you do: 10.12, Xcode 9.2) – the code builds without errors, however when I run Pashua as standalone with a vibrancy setup I still get the `Cfg vibrant invalid` error.

**Comment by BlueM** [comment]
Merged – thanks.

**Pull request merged**
